steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - -f
      - backend/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/marketplace/backend:${SHORT_SHA}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/marketplace/backend:latest
      - backend

  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/marketplace/backend

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - marketplace-backend
      - --region=${_REGION}
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/marketplace/backend:${SHORT_SHA}
      - --platform=managed
      - --no-allow-unauthenticated

substitutions:
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s
